*
* generated by GAME-CC compiler
*   from TinyGalaxy.game
*
	ORG	$2000
main	EQU	*
.LN0	EQU	*
	STS	_RETSP
	JSR	INIT_MUSIC
.LN1	EQU	*
; (ND_LINENUM 10 '10 [=1 Q2T4P3レ#フラP0RP7ラP1RラRラP3RR%')
; debug dump_loc_table()
; (ND_MUSIC str='Q2T4P3レ#フラP0RP7ラP1RラRラP3RR%' )
; .LL0='Q2T4P3レ#フラP0RP7ラP1RラRラP3RR%'
	LDX	#.LL0
	JSR	MUSIC
	CLI
; (ND_LINENUM 20 '20 Z=$1000 [=1 T1P0% >=$FFEF T=0 S=0 R=0')
.LN20	EQU	*
; debug dump_loc_table()
; (ND_SETVAR str=Z (ND_NUM 4096))
	LDX	#4096
	STX	_Z
; (ND_MUSIC str='T1P0%' )
; .LL1='T1P0%'
	LDX	#.LL1
	JSR	MUSIC
	CLI
; (ND_CALL)
	JSR	$FFEF
	STAB	_CALLRET+1
	STAA	_CALLRET
; (ND_SETVAR str=T (ND_NUM 0))
	LDX	#0
	STX	_T
; (ND_SETVAR str=S (ND_NUM 0))
	STX	_S
; (ND_SETVAR str=R (ND_NUM 0))
	STX	_R
; (ND_LINENUM 30 '30 M=$3D0 M:0)=$9E F=$0A+1 F=F(0)')
.LN30	EQU	*
; debug dump_loc_table()
; (ND_SETVAR str=M (ND_NUM 976))
	LDX	#976
	STX	_M
; (ND_ASSIGN (ND_ARRAY1 str=M (ND_NUM 0)) (ND_NUM 158))
	LDAB	#158
	STAB	0,X
; (ND_SETVAR str=F (ND_NUM 11))
	LDX	#11
	STX	_F
; (ND_SETVAR str=F (ND_ARRAY2 str=F (ND_NUM 0)))
	LDX	0,X
	STX	_F
; (ND_LINENUM 40 '40 V=1 U=$123 U:0)=7 U:1)=5 ^=0 "SCORE:" ?=S')
; debug dump_loc_table()
; 0 LOC_LVAR   : reg X, var F
; 2 LOC_CONST  : reg B, 158
; (ND_SETVAR str=V (ND_NUM 1))
	LDX	#1
	STX	_V
; (ND_SETVAR str=U (ND_NUM 291))
	LDX	#291
	STX	_U
; (ND_ASSIGN (ND_ARRAY1 str=U (ND_NUM 0)) (ND_NUM 7))
	LDAB	#7
	STAB	0,X
; (ND_ASSIGN (ND_ARRAY1 str=U (ND_NUM 1)) (ND_NUM 5))
	LDAB	#5
	STAB	1,X
; (ND_SETCURSOR (ND_NUM 0))
	LDX	#0
	STX	_CURSOR
; (ND_PRINTSTR 'SCORE:')
; .LL2='SCORE:'
	LDX	#.LL2
	JSR	PRINTSTR
; (ND_PRINT (ND_VAR str=S))
	LDAB	_S+1
	LDAA	_S
	JSR	PRINTL
; (ND_LINENUM 50 '50 T=T+1 ;=T=4 T=0')
.LN50	EQU	*
; debug dump_loc_table()
; (ND_INCVAR str=T)
	LDX	_T
	INX
	STX	_T
; (ND_IF (== (ND_VAR str=T) (ND_NUM 4)))
	CPX	#4
	BEQ	.LL5
	JMP	.LN60
.LL5	EQU	*
; (ND_SETVAR str=T (ND_NUM 0))
	LDX	#0
	STX	_T
; (ND_LINENUM 60 '60 M:0)=$9E #=140')
.LN60	EQU	*
; debug dump_loc_table()
; (ND_ASSIGN (ND_ARRAY1 str=M (ND_NUM 0)) (ND_NUM 158))
	LDX	_M
	LDAB	#158
	STAB	0,X
; (ND_GOTO 140)
	JMP	.LN140
; (ND_LINENUM 70 '70 ;=M:0)>7 #=120')
.LN70	EQU	*
; debug dump_loc_table()
; (ND_IFGOTO val=120 (>= (ND_ARRAY1 str=M (ND_NUM 0)) (ND_NUM 8)))
	LDX	_M
	LDAB	0,X
	CLRA
	SUBB	#8
	SBCA	#0
	BLT	.LL9
	JMP	.LN120
.LL9	EQU	*
; (ND_LINENUM 80 '80 S=S+('4*50) R=S/100')
; debug dump_loc_table()
; 0 LOC_LVAR   : reg X, var M
; (ND_SETVAR str=S (+ (* (ND_RAND (ND_NUM 4)) (ND_NUM 50)) (ND_VAR str=S)))
	LDAB	#4
	CLRA
	JSR	RANDOM
	STAB	_TMP0+1
	STAA	_TMP0
	LDAB	#50
	CLRA
	LDX	#_TMP0
	JSR	MULTIPLY
	ADDB	_S+1
	ADCA	_S
	STAB	_S+1
	STAA	_S
; (ND_SETVAR str=R (/ (ND_VAR str=S) (ND_NUM 100)))
	STAB	_TMP0+1
	STAA	_TMP0
	LDAB	#100
	CLRA
	LDX	#_TMP0
	JSR	DIVIDE
	STAB	_R+1
	STAA	_R
; (ND_LINENUM 90 '90 I=1,10 U:0)=$9D U:1)=$9D [=1 シ%')
; debug dump_loc_table()
; 0 LOC_LVAR   : reg D, var R
; (ND_FOR str=I label=1 (ND_SETVAR str=I (ND_NUM 1)) (ND_NUM 11))
; (ND_SETVAR str=I (ND_NUM 1))
	LDX	#1
	STX	_I
; ND_FOR I opt=0
; ND_FOR end of conttol var I
.LF1	EQU	*
; (ND_ASSIGN (ND_ARRAY1 str=U (ND_NUM 0)) (ND_NUM 157))
	LDX	_U
	LDAB	#157
	STAB	0,X
; (ND_ASSIGN (ND_ARRAY1 str=U (ND_NUM 1)) (ND_NUM 157))
	STAB	1,X
; (ND_MUSIC str='シ%' )
; .LL11='シ%'
	LDX	#.LL11
	JSR	MUSIC
	CLI
; (ND_LINENUM 100 '100 U:0)=32 U:1)=32 [=1 ソ%')
; debug dump_loc_table()
; (ND_ASSIGN (ND_ARRAY1 str=U (ND_NUM 0)) (ND_NUM 32))
	LDX	_U
	LDAB	#32
	STAB	0,X
; (ND_ASSIGN (ND_ARRAY1 str=U (ND_NUM 1)) (ND_NUM 32))
	STAB	1,X
; (ND_MUSIC str='ソ%' )
; .LL12='ソ%'
	LDX	#.LL12
	JSR	MUSIC
	CLI
; (ND_LINENUM 110 '110 @=I+1 M:32)=32 #=30')
; debug dump_loc_table()
; (ND_NEXT label=1 str=I (+ (ND_VAR str=I) (ND_NUM 1)))
; ND_NEXT (ND_NEXT label=1 str=I (+ (ND_VAR str=I) (ND_NUM 1)))
; optimize? 0
; node->lhs->lhs:(ND_VAR str=I)
	LDAB	_I+1
	LDAA	_I
	ADDB	#1
	ADCA	#0
	STAB	_I+1
	STAA	_I
; FORTO[node->val].val=11
	SUBB	#11
	SBCA	#0
	BPL	.LL13
	JMP	.LF1
.LL13	EQU	*
; (ND_ASSIGN (ND_ARRAY1 str=M (ND_NUM 32)) (ND_NUM 32))
	LDX	_M
	LDAB	#32
	STAB	32,X
; (ND_GOTO 30)
	JMP	.LN30
; (ND_LINENUM 120 '120 ^=10*256+10 "GAME OVER" I=1,10 M:0)=$2A [=1 ソ%')
.LN120	EQU	*
; debug dump_loc_table()
; (ND_SETCURSOR (ND_NUM 2570))
	LDX	#2570
	STX	_CURSOR
; (ND_PRINTSTR 'GAME OVER')
; .LL14='GAME OVER'
	LDX	#.LL14
	JSR	PRINTSTR
; (ND_FOR str=I label=2 (ND_SETVAR str=I (ND_NUM 1)) (ND_NUM 11))
; (ND_SETVAR str=I (ND_NUM 1))
	LDX	#1
	STX	_I
; ND_FOR I opt=0
; ND_FOR end of conttol var I
.LF2	EQU	*
; (ND_ASSIGN (ND_ARRAY1 str=M (ND_NUM 0)) (ND_NUM 42))
	LDX	_M
	LDAB	#42
	STAB	0,X
; (ND_MUSIC str='ソ%' )
; .LL15='ソ%'
	LDX	#.LL15
	JSR	MUSIC
	CLI
; (ND_LINENUM 121 '121 M:0)=32 [=1 シ% @=I+1')
; debug dump_loc_table()
; (ND_ASSIGN (ND_ARRAY1 str=M (ND_NUM 0)) (ND_NUM 32))
	LDX	_M
	LDAB	#32
	STAB	0,X
; (ND_MUSIC str='シ%' )
; .LL16='シ%'
	LDX	#.LL16
	JSR	MUSIC
	CLI
; (ND_NEXT label=2 str=I (+ (ND_VAR str=I) (ND_NUM 1)))
; ND_NEXT (ND_NEXT label=2 str=I (+ (ND_VAR str=I) (ND_NUM 1)))
; optimize? 0
; node->lhs->lhs:(ND_VAR str=I)
	LDAB	_I+1
	LDAA	_I
	ADDB	#1
	ADCA	#0
	STAB	_I+1
	STAA	_I
; FORTO[node->val].val=11
	SUBB	#11
	SBCA	#0
	BPL	.LL17
	JMP	.LF2
.LL17	EQU	*
; (ND_LINENUM 130 '130*POKE $82,0:POKE $83,0:RUN')
; debug dump_loc_table()
; (ND_REM str="*POKE $82,0:POKE $83,0:RUN")
; (ND_LINENUM 131 '131 [=1 T4P1トRトRミRソP2フP9R%')
; debug dump_loc_table()
; (ND_MUSIC str='T4P1トRトRミRソP2フP9R%' )
; .LL18='T4P1トRトRミRソP2フP9R%'
	LDX	#.LL18
	JSR	MUSIC
	CLI
; (ND_LINENUM 132 '132 #=20')
; debug dump_loc_table()
; (ND_GOTO 20)
	JMP	.LN20
; (ND_LINENUM 140 '140 M:0)=32 M:32)=32')
.LN140	EQU	*
; debug dump_loc_table()
; (ND_ASSIGN (ND_ARRAY1 str=M (ND_NUM 0)) (ND_NUM 32))
	LDX	_M
	LDAB	#32
	STAB	0,X
; (ND_ASSIGN (ND_ARRAY1 str=M (ND_NUM 32)) (ND_NUM 32))
	STAB	32,X
; (ND_LINENUM 150 '150*A=[ ;=A="V" M=M-1')
; debug dump_loc_table()
; 0 LOC_LVAR   : reg X, var M
; 1 LOC_CONST  : reg B, 32
; (ND_REM str="*A=[ ;=A="V" M=M-1")
; (ND_LINENUM 151 '151*;=A="N" M=M+1')
; debug dump_loc_table()
; 0 LOC_LVAR   : reg X, var M
; 1 LOC_CONST  : reg B, 32
; (ND_REM str="*;=A="N" M=M+1")
; (ND_LINENUM 153 '153* $10:英数,$20:英記号,$40:カナ,$80:カナ記号')
; debug dump_loc_table()
; 0 LOC_LVAR   : reg X, var M
; 1 LOC_CONST  : reg B, 32
; (ND_REM str="* $10:英数,$20:英記号,$40:カナ,$80:カナ記号")
; (ND_LINENUM 154 '154 X=$EEC0 ;=X:0)&$20=0 M=M-1')
; debug dump_loc_table()
; 0 LOC_LVAR   : reg X, var M
; 1 LOC_CONST  : reg B, 32
; (ND_SETVAR str=X (ND_NUM 61120))
	LDX	#61120
	STX	_X
; (ND_IF (== (ND_BITAND (ND_ARRAY1 str=X (ND_NUM 0)) (ND_NUM 32)) (ND_NUM 0)))
	LDAB	0,X
	CLRA
	ANDB	#32
	CMPB	#0
	BNE	.LL22
	CMPA	#0
	BEQ	.LL21
.LL22	EQU	*
	JMP	.LN155
.LL21	EQU	*
; (ND_DECVAR str=M)
	LDX	_M
	DEX
	STX	_M
; (ND_LINENUM 155 '155         ;=X:0)&$40=0 M=M+1')
.LN155	EQU	*
; debug dump_loc_table()
; (ND_IF (== (ND_BITAND (ND_ARRAY1 str=X (ND_NUM 0)) (ND_NUM 64)) (ND_NUM 0)))
	LDX	_X
	LDAB	0,X
	CLRA
	ANDB	#64
	CMPB	#0
	BNE	.LL26
	CMPA	#0
	BEQ	.LL25
.LL26	EQU	*
	JMP	.LN156
.LL25	EQU	*
; (ND_INCVAR str=M)
	LDX	_M
	INX
	STX	_M
; (ND_LINENUM 156 '156         ;=X:0)&$80=0 M=M+1')
.LN156	EQU	*
; debug dump_loc_table()
; (ND_IF (== (ND_BITAND (ND_ARRAY1 str=X (ND_NUM 0)) (ND_NUM 128)) (ND_NUM 0)))
	LDX	_X
	LDAB	0,X
	CLRA
	ANDB	#128
	CMPB	#0
	BNE	.LL30
	CMPA	#0
	BEQ	.LL29
.LL30	EQU	*
	JMP	.LN160
.LL29	EQU	*
; (ND_INCVAR str=M)
	LDX	_M
	INX
	STX	_M
; (ND_LINENUM 160 '160 X=$EEC0 ;=X:0)&$10 ;=%(T/2) #=180')
.LN160	EQU	*
; debug dump_loc_table()
; (ND_SETVAR str=X (ND_NUM 61120))
	LDX	#61120
	STX	_X
; (ND_IF (ND_BITAND (ND_ARRAY1 str=X (ND_NUM 0)) (ND_NUM 16)))
	LDAB	0,X
	CLRA
	ANDB	#16
	TSTB
	BNE	.LL31
	JMP	.LN170
.LL31	EQU	*
; (ND_IFGOTO val=180 (ND_ANDI_MOD (ND_VAR str=T) val=1))
	LDAB	_T+1
	LDAA	_T
	ANDB	#1
	CLRA
	STAB	_MOD+1
	STAA	_MOD
	TSTB
	BNE	.LL33
	TSTA
	BEQ	.LL34
.LL33	EQU	*
	JMP	.LN180
.LL34	EQU	*
; (ND_LINENUM 170 '170 M=M-$20 ;=M<$120 M=$3D0')
.LN170	EQU	*
; debug dump_loc_table()
; (ND_SETVAR str=M (+ (ND_VAR str=M) (ND_NUM -32)))
	LDAB	_M+1
	LDAA	_M
	ADDB	#224
	ADCA	#255
	STAB	_M+1
	STAA	_M
; (ND_IF (< (ND_VAR str=M) (ND_NUM 288)))
	SUBB	#32
	SBCA	#1
	BLT	.LL37
.LL38	EQU	*
	JMP	.LN180
.LL37	EQU	*
; (ND_SETVAR str=M (ND_NUM 976))
	LDX	#976
	STX	_M
; (ND_LINENUM 180 '180 ;=M:0)<>$20 ;=M:0)<>$9E #=70')
.LN180	EQU	*
; debug dump_loc_table()
; (ND_IF (!= (ND_ARRAY1 str=M (ND_NUM 0)) (ND_NUM 32)))
	LDX	_M
	LDAB	0,X
	CMPB	#32
	BNE	.LL41
	JMP	.LN190
.LL41	EQU	*
; (ND_IFGOTO val=70 (!= (ND_ARRAY1 str=M (ND_NUM 0)) (ND_NUM 158)))
	LDAB	0,X
	CMPB	#158
	BEQ	.LL45
	JMP	.LN70
.LL45	EQU	*
; (ND_LINENUM 190 '190 M:0)=$9E ;=X:0)=239 M:32)=$1A')
.LN190	EQU	*
; debug dump_loc_table()
; (ND_ASSIGN (ND_ARRAY1 str=M (ND_NUM 0)) (ND_NUM 158))
	LDX	_M
	LDAB	#158
	STAB	0,X
; (ND_IF (== (ND_ARRAY1 str=X (ND_NUM 0)) (ND_NUM 239)))
	LDX	_X
	LDAB	0,X
	CMPB	#239
	BEQ	.LL49
	JMP	.LN200
.LL49	EQU	*
; (ND_ASSIGN (ND_ARRAY1 str=M (ND_NUM 32)) (ND_NUM 26))
	LDX	_M
	LDAB	#26
	STAB	32,X
; (ND_LINENUM 200 '200 ;=T #=250')
.LN200	EQU	*
; debug dump_loc_table()
; (ND_IFGOTO val=250 (ND_VAR str=T))
	LDX	_T
	BEQ	.LL52
	JMP	.LN250
.LL52	EQU	*
; (ND_LINENUM 210 '210 U:0)=32 U:1)=32')
; debug dump_loc_table()
; 0 LOC_LVAR   : reg X, var T
; (ND_ASSIGN (ND_ARRAY1 str=U (ND_NUM 0)) (ND_NUM 32))
	LDX	_U
	LDAB	#32
	STAB	0,X
; (ND_ASSIGN (ND_ARRAY1 str=U (ND_NUM 1)) (ND_NUM 32))
	STAB	1,X
; (ND_LINENUM 220 '220 ;='8=1 V=-V')
; debug dump_loc_table()
; 0 LOC_LVAR   : reg X, var U
; 1 LOC_CONST  : reg B, 32
; (ND_IF (== (ND_RAND (ND_NUM 8)) (ND_NUM 1)))
	LDAB	#8
	CLRA
	JSR	RANDOM
	CMPB	#1
	BNE	.LL56
	CMPA	#0
	BEQ	.LL55
.LL56	EQU	*
	JMP	.LN230
.LL55	EQU	*
; (ND_NEGVAR str=V)
	NEG	_V+1
	BNE	.LL57
	DEC	_V
.LL57	COM	_V
; (ND_LINENUM 230 '230 U=U+V ;=U<$124 V=1')
.LN230	EQU	*
; debug dump_loc_table()
; (ND_SETVAR str=U (+ (ND_VAR str=U) (ND_VAR str=V)))
	LDAB	_U+1
	LDAA	_U
	ADDB	_V+1
	ADCA	_V
	STAB	_U+1
	STAA	_U
; (ND_IF (< (ND_VAR str=U) (ND_NUM 292)))
	SUBB	#36
	SBCA	#1
	BLT	.LL60
.LL61	EQU	*
	JMP	.LN231
.LL60	EQU	*
; (ND_SETVAR str=V (ND_NUM 1))
	LDX	#1
	STX	_V
; (ND_LINENUM 231 '231 ;=U>$138 V=-1')
.LN231	EQU	*
; debug dump_loc_table()
; (ND_IF (>= (ND_VAR str=U) (ND_NUM 313)))
	LDAB	_U+1
	LDAA	_U
	SUBB	#57
	SBCA	#1
	BGE	.LL64
.LL65	EQU	*
	JMP	.LN240
.LL64	EQU	*
; (ND_SETVAR str=V (ND_NUM -1))
	LDX	#-1
	STX	_V
; (ND_LINENUM 240 '240 U:0)=7 U:1)=5')
.LN240	EQU	*
; debug dump_loc_table()
; (ND_ASSIGN (ND_ARRAY1 str=U (ND_NUM 0)) (ND_NUM 7))
	LDX	_U
	LDAB	#7
	STAB	0,X
; (ND_ASSIGN (ND_ARRAY1 str=U (ND_NUM 1)) (ND_NUM 5))
	LDAB	#5
	STAB	1,X
; (ND_LINENUM 250 '250 !=1000 !=1100 !=1020 !=1040 !=1080')
.LN250	EQU	*
; debug dump_loc_table()
; (ND_GOSUB 1000)
	JSR	.LN1000
; (ND_GOSUB 1100)
	JSR	.LN1100
; (ND_GOSUB 1020)
	JSR	.LN1020
; (ND_GOSUB 1040)
	JSR	.LN1040
; (ND_GOSUB 1080)
	JSR	.LN1080
; (ND_LINENUM 255 '255* 敵出現')
; debug dump_loc_table()
; (ND_REM str="* 敵出現")
; (ND_LINENUM 260 '260 P=$140 ;='8=1 P=$120 P:('8-1)*64)=$7C')
; debug dump_loc_table()
; (ND_SETVAR str=P (ND_NUM 320))
	LDX	#320
	STX	_P
; (ND_IF (== (ND_RAND (ND_NUM 8)) (ND_NUM 1)))
	LDAB	#8
	CLRA
	JSR	RANDOM
	CMPB	#1
	BNE	.LL69
	CMPA	#0
	BEQ	.LL68
.LL69	EQU	*
	JMP	.LN270
.LL68	EQU	*
; (ND_SETVAR str=P (ND_NUM 288))
	LDX	#288
	STX	_P
; (ND_ASSIGN (ND_ARRAY1 str=P (* (+ (ND_RAND (ND_NUM 8)) (ND_NUM -1)) (ND_NUM 64))) (ND_NUM 124))
	LDAB	#8
	CLRA
	JSR	RANDOM
	ADDB	#255
	ADCA	#255
	ASLB
	ROLA
	ASLB
	ROLA
	ASLB
	ROLA
	ASLB
	ROLA
	ASLB
	ROLA
	ASLB
	ROLA
	ADDB	_P+1
	ADCA	_P
	STAB	_TMP0+1
	STAA	_TMP0
	LDX	_TMP0
	LDAB	#124
	STAB	0,X
; (ND_LINENUM 270 '270 ;='8=1 P=$13F P:('8-1)*64)=$7B')
.LN270	EQU	*
; debug dump_loc_table()
; (ND_IF (== (ND_RAND (ND_NUM 8)) (ND_NUM 1)))
	LDAB	#8
	CLRA
	JSR	RANDOM
	CMPB	#1
	BNE	.LL73
	CMPA	#0
	BEQ	.LL72
.LL73	EQU	*
	JMP	.LN280
.LL72	EQU	*
; (ND_SETVAR str=P (ND_NUM 319))
	LDX	#319
	STX	_P
; (ND_ASSIGN (ND_ARRAY1 str=P (* (+ (ND_RAND (ND_NUM 8)) (ND_NUM -1)) (ND_NUM 64))) (ND_NUM 123))
	LDAB	#8
	CLRA
	JSR	RANDOM
	ADDB	#255
	ADCA	#255
	ASLB
	ROLA
	ASLB
	ROLA
	ASLB
	ROLA
	ASLB
	ROLA
	ASLB
	ROLA
	ASLB
	ROLA
	ADDB	_P+1
	ADCA	_P
	STAB	_TMP0+1
	STAA	_TMP0
	LDX	_TMP0
	LDAB	#123
	STAB	0,X
; (ND_LINENUM 280 '280 #=50')
.LN280	EQU	*
; debug dump_loc_table()
; (ND_GOTO 50)
	JMP	.LN50
; (ND_LINENUM 1000 '1000* 敵攻撃｜($86)落下')
.LN1000	EQU	*
; debug dump_loc_table()
; (ND_REM str="* 敵攻撃｜($86)落下")
; (ND_LINENUM 1001 '1001 X=$037F')
; debug dump_loc_table()
; (ND_SETVAR str=X (ND_NUM 895))
	LDX	#895
	STX	_X
; (ND_LINENUM 1003 '1003 ;=X:0)=$86 X:$20)=$86 X:0)=$20')
.LN1003	EQU	*
; debug dump_loc_table()
; (ND_IF (== (ND_ARRAY1 str=X (ND_NUM 0)) (ND_NUM 134)))
	LDX	_X
	LDAB	0,X
	CMPB	#134
	BEQ	.LL76
	JMP	.LN1004
.LL76	EQU	*
; (ND_ASSIGN (ND_ARRAY1 str=X (ND_NUM 32)) (ND_NUM 134))
	LDAB	#134
	STAB	32,X
; (ND_ASSIGN (ND_ARRAY1 str=X (ND_NUM 0)) (ND_NUM 32))
	LDAB	#32
	STAB	0,X
; (ND_LINENUM 1004 '1004 X=X-1 ;=X<>$013F #=1003')
.LN1004	EQU	*
; debug dump_loc_table()
; (ND_DECVAR str=X)
	LDX	_X
	DEX
	STX	_X
; (ND_IFGOTO val=1003 (!= (ND_VAR str=X) (ND_NUM 319)))
	CPX	#319
	BEQ	.LL80
	JMP	.LN1003
.LL80	EQU	*
; (ND_LINENUM 1019 '1019 ]')
; debug dump_loc_table()
; 0 LOC_LVAR   : reg X, var X
; ND_RETURN 
	RTS
; (ND_LINENUM 1020 '1020* 敵→($7C)右移動')
.LN1020	EQU	*
; debug dump_loc_table()
; (ND_REM str="* 敵→($7C)右移動")
; (ND_LINENUM 1021 '1021 X=$039F')
; debug dump_loc_table()
; (ND_SETVAR str=X (ND_NUM 927))
	LDX	#927
	STX	_X
; (ND_LINENUM 1023 '1023 ;=X:0)=$7C X:1)=$7C X:0)=$20')
.LN1023	EQU	*
; debug dump_loc_table()
; (ND_IF (== (ND_ARRAY1 str=X (ND_NUM 0)) (ND_NUM 124)))
	LDX	_X
	LDAB	0,X
	CMPB	#124
	BEQ	.LL84
	JMP	.LN1024
.LL84	EQU	*
; (ND_ASSIGN (ND_ARRAY1 str=X (ND_NUM 1)) (ND_NUM 124))
	LDAB	#124
	STAB	1,X
; (ND_ASSIGN (ND_ARRAY1 str=X (ND_NUM 0)) (ND_NUM 32))
	LDAB	#32
	STAB	0,X
; (ND_LINENUM 1024 '1024 X=X-1 ;=X<>$011F #=1023')
.LN1024	EQU	*
; debug dump_loc_table()
; (ND_DECVAR str=X)
	LDX	_X
	DEX
	STX	_X
; (ND_IFGOTO val=1023 (!= (ND_VAR str=X) (ND_NUM 287)))
	CPX	#287
	BEQ	.LL88
	JMP	.LN1023
.LL88	EQU	*
; (ND_LINENUM 1029 '1029 ]')
; debug dump_loc_table()
; 0 LOC_LVAR   : reg X, var X
; ND_RETURN 
	RTS
; (ND_LINENUM 1040 '1040* 敵←($7B)左移動')
.LN1040	EQU	*
; debug dump_loc_table()
; (ND_REM str="* 敵←($7B)左移動")
; (ND_LINENUM 1041 '1041 X=$0120')
; debug dump_loc_table()
; (ND_SETVAR str=X (ND_NUM 288))
	LDX	#288
	STX	_X
; (ND_LINENUM 1043 '1043 ;=X:1)=$7B X:0)=$7B X:1)=$20')
.LN1043	EQU	*
; debug dump_loc_table()
; (ND_IF (== (ND_ARRAY1 str=X (ND_NUM 1)) (ND_NUM 123)))
	LDX	_X
	LDAB	1,X
	CMPB	#123
	BEQ	.LL92
	JMP	.LN1044
.LL92	EQU	*
; (ND_ASSIGN (ND_ARRAY1 str=X (ND_NUM 0)) (ND_NUM 123))
	LDAB	#123
	STAB	0,X
; (ND_ASSIGN (ND_ARRAY1 str=X (ND_NUM 1)) (ND_NUM 32))
	LDAB	#32
	STAB	1,X
; (ND_LINENUM 1044 '1044 X=X+1 ;=X<>$039E #=1043')
.LN1044	EQU	*
; debug dump_loc_table()
; (ND_INCVAR str=X)
	LDX	_X
	INX
	STX	_X
; (ND_IFGOTO val=1043 (!= (ND_VAR str=X) (ND_NUM 926)))
	CPX	#926
	BEQ	.LL96
	JMP	.LN1043
.LL96	EQU	*
; (ND_LINENUM 1049 '1049 ]')
; debug dump_loc_table()
; 0 LOC_LVAR   : reg X, var X
; ND_RETURN 
	RTS
; (ND_LINENUM 1060 '1060* 簡易乱数')
.LN1060	EQU	*
; debug dump_loc_table()
; (ND_REM str="* 簡易乱数")
; (ND_LINENUM 1061 '1061 F=%((F*2!F+1)/256)')
; debug dump_loc_table()
; (ND_SETVAR str=F (ND_MOD (/ (+ (ND_BITXOR (ND_ASLD (ND_VAR str=F) val=1) (ND_VAR str=F)) (ND_NUM 1)) (ND_NUM 256))))
	LDAB	_F+1
	LDAA	_F
	ASLB
	ROLA
	EORB	_F+1
	EORA	_F
	ADDB	#1
	ADCA	#0
	STAB	_TMP0+1
	STAA	_TMP0
	CLRB
	LDAA	#1
	LDX	#_TMP0
	JSR	DIVIDE
	LDAB	_MOD+1
	LDAA	_MOD
	STAB	_F+1
	STAA	_F
; (ND_LINENUM 1069 '1069 ]')
; debug dump_loc_table()
; 0 LOC_LVAR   : reg D, var F
; ND_RETURN 
	RTS
; (ND_LINENUM 1080 '1080* 敵攻撃出現')
.LN1080	EQU	*
; debug dump_loc_table()
; (ND_REM str="* 敵攻撃出現")
; (ND_LINENUM 1081 '1081 X=$037F')
; debug dump_loc_table()
; (ND_SETVAR str=X (ND_NUM 895))
	LDX	#895
	STX	_X
; (ND_LINENUM 1083 '1083 ;=X:0)=$20 #=1089')
.LN1083	EQU	*
; debug dump_loc_table()
; (ND_IFGOTO val=1089 (== (ND_ARRAY1 str=X (ND_NUM 0)) (ND_NUM 32)))
	LDX	_X
	LDAB	0,X
	CMPB	#32
	BNE	.LL100
	JMP	.LN1089
.LL100	EQU	*
; (ND_LINENUM 1084 '1084 ;=X:0)=$86 #=1089')
; debug dump_loc_table()
; 0 LOC_LVAR   : reg X, var X
; (ND_IFGOTO val=1089 (== (ND_ARRAY1 str=X (ND_NUM 0)) (ND_NUM 134)))
	LDAB	0,X
	CMPB	#134
	BNE	.LL104
	JMP	.LN1089
.LL104	EQU	*
; (ND_LINENUM 1085 '1085 !=1060 ;=F<=R ;=X:$20)<>$86 X:$20)=$86')
; debug dump_loc_table()
; 0 LOC_LVAR   : reg X, var X
; (ND_GOSUB 1060)
	JSR	.LN1060
; (ND_IF (<= (ND_VAR str=F) (ND_VAR str=R)))
	LDAB	_F+1
	LDAA	_F
	SUBB	_R+1
	SBCA	_R
	BGT	.LL109
	BNE	.LL108
	TSTB
	BEQ	.LL108
.LL109	EQU	*
	JMP	.LN1089
.LL108	EQU	*
; (ND_IF (!= (ND_ARRAY1 str=X (ND_NUM 32)) (ND_NUM 134)))
	LDX	_X
	LDAB	32,X
	CMPB	#134
	BNE	.LL112
	JMP	.LN1089
.LL112	EQU	*
; (ND_ASSIGN (ND_ARRAY1 str=X (ND_NUM 32)) (ND_NUM 134))
	LDAB	#134
	STAB	32,X
; (ND_LINENUM 1089 '1089 X=X-1')
.LN1089	EQU	*
; debug dump_loc_table()
; (ND_DECVAR str=X)
	LDX	_X
	DEX
	STX	_X
; (ND_LINENUM 1090 '1090 ;=X<>$013F #=1083')
; debug dump_loc_table()
; 0 LOC_LVAR   : reg X, var X
; (ND_IFGOTO val=1083 (!= (ND_VAR str=X) (ND_NUM 319)))
	CPX	#319
	BEQ	.LL116
	JMP	.LN1083
.LL116	EQU	*
; (ND_LINENUM 1091 '1091 ]')
; debug dump_loc_table()
; 0 LOC_LVAR   : reg X, var X
; ND_RETURN 
	RTS
; (ND_LINENUM 1100 '1100* 最下段の敵攻撃消去')
.LN1100	EQU	*
; debug dump_loc_table()
; (ND_REM str="* 最下段の敵攻撃消去")
; (ND_LINENUM 1101 '1101 X=$0380')
; debug dump_loc_table()
; (ND_SETVAR str=X (ND_NUM 896))
	LDX	#896
	STX	_X
; (ND_LINENUM 1103 '1103 ;=X:0)=$86 X:0)=$20')
.LN1103	EQU	*
; debug dump_loc_table()
; (ND_IF (== (ND_ARRAY1 str=X (ND_NUM 0)) (ND_NUM 134)))
	LDX	_X
	LDAB	0,X
	CMPB	#134
	BEQ	.LL120
	JMP	.LN1104
.LL120	EQU	*
; (ND_ASSIGN (ND_ARRAY1 str=X (ND_NUM 0)) (ND_NUM 32))
	LDAB	#32
	STAB	0,X
; (ND_LINENUM 1104 '1104 X=X+1')
.LN1104	EQU	*
; debug dump_loc_table()
; (ND_INCVAR str=X)
	LDX	_X
	INX
	STX	_X
; (ND_LINENUM 1105 '1105 ;=X<>$03A0 #=1103')
; debug dump_loc_table()
; 0 LOC_LVAR   : reg X, var X
; (ND_IFGOTO val=1103 (!= (ND_VAR str=X) (ND_NUM 928)))
	CPX	#928
	BEQ	.LL124
	JMP	.LN1103
.LL124	EQU	*
; (ND_LINENUM 1109 '1109 ]')
; debug dump_loc_table()
; 0 LOC_LVAR   : reg X, var X
; ND_RETURN 
	RTS
.LN65536	EQU	*
	LDS	_RETSP
	RTS
_RETSP	RMB	2
_CPXWK	RMB	2
VAR	EQU	*
_A	RMB	2
_B	RMB	2
_C	RMB	2
_D	RMB	2
_E	RMB	2
_F	RMB	2
_G	RMB	2
_H	RMB	2
_I	RMB	2
_J	RMB	2
_K	RMB	2
_L	RMB	2
_M	RMB	2
_N	RMB	2
_O	RMB	2
_P	RMB	2
_Q	RMB	2
_R	RMB	2
_S	RMB	2
_T	RMB	2
_U	RMB	2
_V	RMB	2
_W	RMB	2
_X	RMB	2
_Y	RMB	2
_Z	RMB	2
_CALLRET	RMB	2
_TIMER	EQU	$000A
_CURSOR	EQU	$000F
_LT1	RMB	2	; .LF1: FOR I
_LT2	RMB	2	; .LF2: FOR I
.LL0	EQU	*
*	Q2T4P3レ#フラP0RP7ラP1RラRラP3RR%
	FCC	'Q2T4P3'
	FCB	$da
	FCC	'#'
	FCB	$cc,$d7
	FCC	'P0RP7'
	FCB	$d7
	FCC	'P1R'
	FCB	$d7
	FCC	'R'
	FCB	$d7
	FCC	'P3RR%'
	FCB	0
.LL1	EQU	*
*	T1P0%
	FCC	'T1P0%'
	FCB	0
.LL2	EQU	*
*	SCORE:
	FCC	'SCORE:'
	FCB	0
.LL11	EQU	*
*	シ%
	FCB	$bc
	FCC	'%'
	FCB	0
.LL12	EQU	*
*	ソ%
	FCB	$bf
	FCC	'%'
	FCB	0
.LL14	EQU	*
*	GAME OVER
	FCC	'GAME OVER'
	FCB	0
.LL15	EQU	*
*	ソ%
	FCB	$bf
	FCC	'%'
	FCB	0
.LL16	EQU	*
*	シ%
	FCB	$bc
	FCC	'%'
	FCB	0
.LL18	EQU	*
*	T4P1トRトRミRソP2フP9R%
	FCC	'T4P1'
	FCB	$c4
	FCC	'R'
	FCB	$c4
	FCC	'R'
	FCB	$d0
	FCC	'R'
	FCB	$bf
	FCC	'P2'
	FCB	$cc
	FCC	'P9R%'
	FCB	0
	INCLUDE	gamecc.asm
_LPGEND	EQU	*
	END	main
* vim:set ts=8:
